### ISSUE TITLE
[BUG] Self-signed certificate

### ISSUE THREAD

**Issue by jhspyhard** [tien/pi-hole-connect#12]
**Describe the bug**
I recently added my network's root CA certificate to my Android device as a User Trusted credential. It is probably worth mentioning that since it is a local area network CA cert, it isn't signed by any of the internet-at-large CAs that would be in my Android system key store and is effectively a self-signed network wide root certificate. My pihole has TLS cert which is signed by this one.

When I dropped in all of the information for my pihole and enabled HTTPS under the advanced setting, and P-HC and attempted to connect, I got the following Java Exception:
`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. Please Check your internet connection or whether the API key has been set.`

**To Reproduce**
Generate a self-signed Root / Intermediate PKI set.
Generate a pihole TLS cert based on Intermediate PKI set and enable on pihole.
Install self-signed Root Certificate to the Android Trust Store
Configure Pihole-Connect to connect to the Pihole over TLS.
See error above.

**Expected behaviour**
I expected the connection to complete successfully and the Pihole to be available within the app.

**Screenshots**
P-HC Pihole Configuration:
![P-HC Pihole Configuration](https://user-images.githubusercontent.com/14208830/114905631-29d89c80-9de7-11eb-8253-ea21996e4af0.jpg)
Java Exception:
![Java Exception](https://user-images.githubusercontent.com/14208830/114905648-2e04ba00-9de7-11eb-8631-cf8a46a6715a.jpg)
Root CA Certificate Details:
![Root CA Certificate Details](https://user-images.githubusercontent.com/14208830/114906133-bdaa6880-9de7-11eb-9c1c-039396cfd8b4.jpg)
Root CA in Android Trust Store:
![Root CA in Android Trust Store](https://user-images.githubusercontent.com/14208830/114906177-c9962a80-9de7-11eb-8c03-aaed156b88cf.jpg)
Pihole Web Interface Certificate View:
![Pihole Web Interface Certificate View](https://user-images.githubusercontent.com/14208830/114906231-d581ec80-9de7-11eb-86a6-a4b0c0523dc7.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 11 ]
 - Browser PiHole Connect 
 - Version v3.0

**Additional context**
Let me know if I missed anything.

**Comment by tien** [comment]
@jhspyhard Thanks for the extremely detailed problem description man, I'll try to push out a fix in the next couple of day 🍻

**Comment by jhspyhard** [comment]
Confirmed working. Thanks for your excellent work! 

![Screenshot_20210421-113142](https://user-images.githubusercontent.com/14208830/115580652-4bc59980-a295-11eb-951e-84afe1a9422c.png)
