### ISSUE TITLE
Please add a button to open the Pi-hole in a web browser

### ISSUE THREAD

**Issue by drakz-AU** [tien/pi-hole-connect#129]
Can you please add a button on the dashboard or in the 3-dot menu to open the web interface of the current Pi-hole in a browser? Thanks

**Comment by tien** [comment]
Thanks for the suggestion @drakz-AU. I'll have this as part of the next release :)

**Comment by drakz-AU** [comment]
Thanks for adding this so quickly!
I just tried it and it seems to direct to port 80 on the configured Pi-hole IP address. My Pi-hole is running in a docker container, so the link opens my host not the Pi-hole dashboard.
Can you please make it so that it also points to the correct port?  (ie. the one configured in settings)
Thanks for your hard work!

**Comment by tien** [comment]
@drakz-AU thanks for raising that issue, this #132 will fixes that.
