### ISSUE TITLE
[BUG] Hamburger menu and some text nearly invisible in device's dark mode

### ISSUE THREAD

**Issue by elmicha** [tien/pi-hole-connect#14]
On my Xiaomi Mi Max 3 in the device's dark mode the hamburger menu and some text is very dark and barely distinguishable from the background:
![Bildschirmfoto vom 2021-04-16 21-08-27](https://user-images.githubusercontent.com/3606386/115074463-04888300-9efa-11eb-81ff-4dfad7193b79.png)
This was with the default System theme of Pi-hole Connect. The text in the tabs Statistics/Logs/Filters has no problems.

With the light mode of Pi-hole Connect it gets a little bit better (the menu dots are clearly visible):
![Bildschirmfoto vom 2021-04-16 21-12-43](https://user-images.githubusercontent.com/3606386/115074740-6b0da100-9efa-11eb-9bf9-8a48c36463c1.png)

With System mode again, the text in Preferences is visible, only the icons are too dark:
![Bildschirmfoto vom 2021-04-16 21-13-27](https://user-images.githubusercontent.com/3606386/115075035-c475d000-9efa-11eb-837d-ec1b313b7b7b.png)

If I switch off the dark mode in the phone's settings and switch on the dark theme of Pi-hole Connect everything is good (but then most other apps are too white):

![Bildschirmfoto vom 2021-04-16 21-16-49](https://user-images.githubusercontent.com/3606386/115075423-57166f00-9efb-11eb-93ff-2d56ac7930d4.png)

The OS is Android 10 with MIUI 12.

Edit: I just remembered that I can disable the system's dark mode for individual apps (at the bottom of the settings page where you can enable dark mode), so I did that. So for me the problem is solved, but other users might have the same problem that they can't see the hamburger menu when they start the app for the first time.

Thank you for the great app!

**Comment by tien** [comment]
Hi, thanks for reporting this issue. It's rather unique since it's related to the launcher that you are using. It appeared that the launcher tried to manually apply dark theme to the app. Sadly it can't be fix since there's no way to detect this. Glad to hear that you can disable it for the app though 😄
