### ISSUE TITLE
Translation into other languages 

### ISSUE THREAD

**Issue by Akszyn** [tien/pi-hole-connect#180]
Polish language is missing but I will be happy to help translate so please link to a folder where I can add the missing language

**Comment by tien** [comment]
Hey @Akszyn yes would be great if you want to help out on this, here's example of how the translation work:

- Original English version: https://github.com/tien/pi-hole-connect/blob/main/app/src/main/res/values/strings.xml
- German version: https://github.com/tien/pi-hole-connect/blob/main/app/src/main/res/values-de/strings.xml

**Comment by Akszyn** [comment]
@tien Could I please create a folder and a file on github for adding a new language because the only thing I guess from this page I can add or edit the file in the folder

**Comment by tien** [comment]
Sure thing, I've created a template file that can be edited here: https://github.com/tien/pi-hole-connect/pull/183/files

**Comment by Akszyn** [comment]
Please make this translation available as a beta version of the application because you can always correct something easier and when you will be able to download applications with an additional language

**Comment by tien** [comment]
Thank you for the PR, sorry I haven't got much time outside of work to look at this earlier. Will get this released tonight :)

I've made it so that future PRs will also have the APK file attached to them now so you can easily check the translation yourself https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts

**Comment by Akszyn** [comment]
I noticed a few mistakes at the arrangement of subtitles marked in red

![Screenshot_2023-11-29-10-39-21-536-edit_com tien piholeconnect](https://github.com/tien/pi-hole-connect/assets/57450821/1fa0becc-3a52-4758-b90e-cfc06e8b384b)

needs some minor tweaks in the centering of the text
