### ISSUE TITLE
Graph x-axis shows incorrect times

### ISSUE THREAD

**Issue by gumbald** [tien/pi-hole-connect#181]
**Describe the bug**
Graph that shows "last 24 hours" shows right-most time as ~12 hours earlier than current time. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Show graph on main view

**Expected behaviour**
Times for graph span last 24 hours 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14

![Screenshot_20231021-191717.png](https://github.com/tien/pi-hole-connect/assets/1609507/ed306eda-bbff-4df5-9d7c-4602e52ff89f)

**Comment by tien** [comment]
Thanks for bringing this to my attention
