### ISSUE TITLE
[BUG] Input Masking on IPv4 address

### ISSUE THREAD

**Issue by martin0641** [tien/pi-hole-connect#72]
**Describe the bug**

I was a dummy and I forgot the last period when I typed 192.168.1.4 and instead typed 192.168.14 and the software accepted that instead of signaling somehow that the input wasn't valid.

Maybe validate the 4 periods, and allowable numbers, and affix a /32 greyed out prefix after the address so that people know they can only be one host.

Because why not 🙂

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tien** [comment]
Thanks for pointing this out, but it's rather tricky since pi.hole allow you to add custom DNS entries. For example `pi.hole` is a valid default address, you can even have `🦄.🔥` pointed to your pi.hole as well.

**Comment by martin0641** [comment]
Fair enough, thank you for responding :)

I'm an engineer too, if you think it warrants it - maybe there is a third
way?

One box for IP, and another for DNS?

My issue is fixed, just wanted to toss that out there - happy trails!

-CM
