### ISSUE TITLE
API key has been set?

### ISSUE THREAD

**Issue by AmusedPocket** [tien/pi-hole-connect#77]
Hello!

This was working earlier, but recently keep getting this error. I can still see the internet traffic. How do I get pass it?

![Screenshot_20211219-223258](https://user-images.githubusercontent.com/88810051/146722507-908aaf75-5878-42db-bdb6-5e73ffaf2e68.png)

Thanks!

**Comment by AmusedPocket** [comment]
I am so sorry I just figured it out.

**Comment by Javtolt** [comment]
How did you solve it? 

> I am so sorry I just figured it out.

How did you solve it?
