### ISSUE TITLE
[BUG]

No longer will connect since updating to pihole FTL V5.15

### ISSUE THREAD

**Issue by ytsejam1138** [tien/pi-hole-connect#95]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cyb3rsinn3r** [comment]
When launching the app, I'm immediately presented with an error message about my internet connection or the API key. 

I've removed the pihole from preferences and added it again. Doesn't matter if I use the IP address of the pihole or the hostname. I've also verified the API key. 
![Screenshot_20220421-210347_Pi-hole Connect](https://user-images.githubusercontent.com/54448156/164588301-9fbdbafb-1e01-4c25-bf56-a4c761c65b2f.jpg)

**Comment by cyb3rsinn3r** [comment]
I ran a tcpdump on the RPi and I do see the request come in and the RPi respond. 
![Screenshot_20220421-211305_JuiceSSH](https://user-images.githubusercontent.com/54448156/164589404-ccde6326-f4fd-49b4-8833-526ee4b51aef.jpg)

**Comment by tien** [comment]
Cool, thanks for the detailed issue report, I have fixed the issue with the home screen. The Log screen however was a bug with pi.hole v5.10. The response returned had content type set to `html/text` by mistake, should have been `application/json`

If you can you also create an issue report on pi.hole repository, else I can create one later today

**Comment by cyb3rsinn3r** [comment]
@tien - thanks for your quick response! I've submitted bug #4710 on the pihole repo.
